# Loki configuration file for a single-node setup with improved settings
# Authentication is disabled as per original configuration
auth_enabled: false

# Server configuration for HTTP and gRPC communication
server:
  http_listen_port: 3100

# Ingester configuration for handling log streams
ingester:
  lifecycler:
    address: 127.0.0.1 # Explicitly bind to localhost for single-node
    ring:
      kvstore:
        store: inmemory # In-memory store for simplicity in single-node setup
      replication_factor: 1 # Single replica for single-node deployment
    final_sleep: 0s # Disable sleep before shutdown for faster restarts
  wal:
    enabled: true
    dir: /tmp/loki/wal
    flush_on_shutdown: true # Ensure WAL is flushed on shutdown
  chunk_idle_period: 30m # Flush chunks after 30 minutes of inactivity
  max_chunk_age: 1h # Force flush chunks after 1 hour
  chunk_target_size: 1572864 # Target chunk size (1.5MB) for efficient compression

# Schema configuration for log storage
schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb # Use TSDB for efficient storage
      object_store: filesystem # Store chunks in filesystem
      schema: v13 # Latest schema version for TSDB
      index:
        prefix: index_ # Index prefix for organization
        period: 24h # Daily index period for manageable index sizes

# Storage configuration for chunks and indexes
storage_config:
  filesystem:
    directory: /tmp/loki/chunks # Directory for chunk storage
  boltdb_shipper:
    active_index_directory: /tmp/loki/index # Directory for active indexes
    cache_location: /tmp/loki/cache # Cache for index shipping
  tsdb_shipper:
    active_index_directory: /tmp/loki/tsdb-index # Dedicated TSDB index directory
    cache_location: /tmp/loki/tsdb-cache # Dedicated TSDB cache

# Limits configuration to control resource usage and retention
limits_config:
  allow_structured_metadata: true # Enable structured metadata for richer querying
  volume_enabled: true # Enable volume metrics for monitoring
  retention_period: 720h # Retain logs for 30 days
  max_query_length: 721h # Allow queries up to retention period + 1h
  max_query_parallelism: 32 # Increase parallelism for faster queries
  ingestion_rate_mb: 4 # Limit ingestion rate to 4MB/s
  ingestion_burst_size_mb: 6 # Allow bursts up to 6MB
  max_streams_per_user: 10000 # Reasonable limit for stream cardinality

# Common configuration for shared paths and storage
common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1 # Single-node setup
  ring:
    kvstore:
      store: inmemory # Consistent with ingester ring

# Compactor configuration for retention and cleanup
compactor:
  working_directory: /tmp/loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  delete_request_store: filesystem
